// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55XGC8I_bDoAYSng8j_OpqdcJhHMhhqM',
    appId: '1:958117647184:web:8fe759396b7b07940f9255',
    messagingSenderId: '958117647184',
    projectId: 'verification-a0cc3',
    authDomain: 'verification-a0cc3.firebaseapp.com',
    storageBucket: 'verification-a0cc3.appspot.com',
    measurementId: 'G-6N174WE902',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeAZ3CxtV_rlCvNMqmen2SLLh_3PLdXY',
    appId: '1:958117647184:android:ed7f7abbade8de9e0f9255',
    messagingSenderId: '958117647184',
    projectId: 'verification-a0cc3',
    storageBucket: 'verification-a0cc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyM7NIr-1tVYsUbgl2nvAGW3VcvHiDb4',
    appId: '1:958117647184:ios:8e8026db52fc0c660f9255',
    messagingSenderId: '958117647184',
    projectId: 'verification-a0cc3',
    storageBucket: 'verification-a0cc3.appspot.com',
    androidClientId: '958117647184-cqu6aq6ukfo43gv8q3fk2cqe82mof70a.apps.googleusercontent.com',
    iosClientId: '958117647184-bi9d15vmhfcjoaib49fv1egi4fg9e44u.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADyM7NIr-1tVYsUbgl2nvAGW3VcvHiDb4',
    appId: '1:958117647184:ios:8e8026db52fc0c660f9255',
    messagingSenderId: '958117647184',
    projectId: 'verification-a0cc3',
    storageBucket: 'verification-a0cc3.appspot.com',
    androidClientId: '958117647184-cqu6aq6ukfo43gv8q3fk2cqe82mof70a.apps.googleusercontent.com',
    iosClientId: '958117647184-bi9d15vmhfcjoaib49fv1egi4fg9e44u.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenManagement',
  );
}
